### ISSUE TITLE
API response 502, error log says No such file or directory   at Database.initEnv

### ISSUE THREAD

**Issue by longnight** [MoneroOcean/nodejs-pool#48]
Hi guys,
this is my first time try to deploy the pool on server, then I got the  502 error response from API endpoint and login endpoint, after running the deploy script. Check the pm2 error logs, what it says as below. How to fix it ?  

```
Error: No such file or directory
    at Database.initEnv (/home/pooluser/nodejs-pool/lib/local_comms.js:29:29)
    at /home/pooluser/nodejs-pool/init.js:54:21
    at tryCatcher (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/pooluser/nodejs-pool/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by MoneroOcean** [comment]
Something wrong with your pool_db directory or access right to it. Not sure. Never saw this.

**Comment by bobbieltd** [comment]
The bash file won't work as before because a lot of changes made by time. You should run the bash manually line by line and if errors, try to fix it by Google.
For the error :  
mkdir ~/pool_db
chown $USER ~/pool_db

However, I doubt there will be still other many errors.

**Comment by longnight** [comment]
Thanks for pointing out that about `~/pool_db/` path. When I ran bash script line by line I lost the variable $CURUSER, that cause `db_storage_path` value was `/home//pool_db/`, after fixed this it work.
